### ISSUE TITLE
When suspension camera is selected it should be on the inside of corner

### ISSUE THREAD

**Issue by PascalHigelin** [vipoo/iRacingReplayOverlay.net#15]
Cameras are selected randomly in a set. When a suspension camera is selected one time out of two it is an outside of corner camera. The following or preceding car being on the inside and the view angle being reduced by the car body, the camera is looking to a place where there is no car

**Comment by LGRDDOG** [comment]
The only way I've been able to work around iRacing's inability to tell if the camera is on the inside or outside of a corner is to not use the suspension cameras at all, and instead, use multiple "Chase" style cameras instead, with it set to focus on group, instead of fixed or car (You'll need to fill in the dampening check-box for this as well).  This way you can position the camera slightly higher to be able to see above the body, while still keeping most of the suspension in view, and the camera will "pan" about to try keeping any vehicles that could be in the shot, actually in the shot.
