### ISSUE TITLE
1.0.3.55 - General settings not taking affect

### ISSUE THREAD

**Issue by ChrisJackson3** [vipoo/iRacingReplayOverlay.net#85]
Tried doing a highlight yesterday using .55 ver, but it doesn't seem to want to go by the settings. Had it set to basically stay on my car, (preferred driver setting), but it still bounced around different cars. On start of race, it wouldn't stay on leader more than just a few seconds regardless of what it was set to.

Anyone have suggestions on the "general" settings? Configure camera settings too.

Data should be sent.

**Comment by LGRDDOG** [comment]
Possibly a screenshot of your current settings may help for those that don't have access to the automatic data, however I do believe that this program was never intended to stay on on vehicle.

Even if you have it set to select battles only for your preferred drivers, and you only have yourself, it WILL jump around to other vehicles if your driver specifically is not in a "Battle" (within the seconds set for battle) as well as it will factor in your "Battle Factor" setting, and if that is set to anything higher than 1, and you're closer to the back of the pack, you won't even ben considered at that point.

Just in case it helps, this is the general configuration that I use for all of my highlight reels.  The only thing that I change ever is the highlight length, which I adjust to ~20% of the actual race length.

![replaydirectorconfig](https://cloud.githubusercontent.com/assets/18492147/15086486/67e44a84-139e-11e6-9b52-9782230f86a0.jpg)

**Comment by ChrisJackson3** [comment]
![1configure video capture](https://cloud.githubusercontent.com/assets/19223105/15090847/0ea18e76-13eb-11e6-938e-b624aacdf1ed.png)
![2configure video capture](https://cloud.githubusercontent.com/assets/19223105/15090849/16b0049e-13eb-11e6-8c46-8afe54b84bd3.png)

**Comment by ChrisJackson3** [comment]
As you pointed out, there are issues with these settings. It was an attempt to get it to focus more on up front action, as well as my car more, and less on junk happening at the back of the field. This is definitely trial and error till some kind of good range is determined.

**Comment by ChrisJackson3** [comment]
Tried your settings Michel. When it was done with the recording it decided there was an error so it didn't encode. Something about couldn't find the file, so I guess I have the locations messed up. Box is checked to send Dean data.

**Comment by ChrisJackson3** [comment]
Observations as I watched it record....from a oval stock car perspective...

---the logic of when the camera changes is not right. I think the random factor is messing with it. It keeps changing cameras when it appears there is no reason for it.

---It doesn't focus any on the "preferred car".

---On starts, it doesn't stay on the leader for more than maybe 2 seconds, then it goes to the last car in that pack, so you miss all the important action. With the settings I tried, Not once did it actually show the leader start. It kept switching to the end car of the lead group.

---Cautions...it gets stuck on the last car it was on when the yellow comes out. Instead it needs to change to the leader, or the preferred car, under caution.

---On a start, it should stay focused on the lead pack for at least 3-4 laps, maybe go to close action in the top 10, then right back to the leader or preferred car.

---Seems to be no reason for the changes it makes camera to camera. Needs to be a way to override randomness. It appears the random logic is overriding any settings.

---The primary focus needs to be either on the leader, or the preferred car. User should be able to choose which one like a check box or something.

---When a caution comes out, show the incident, but then change right back to the leader or preferred car. This would show who is pitting, etc. Nobody cares what is happening in general in the back of the field. The focus should be on the leaders.

---Need to have it not switch to the last car in line on a start. It's not relevant at all.

**Comment by ChrisJackson3** [comment]
Where do I download the full source code for Replay Director? I want it so I can try to find a C# progammer.

**Comment by LGRDDOG** [comment]
I was going to ask you if your replays are for oval or road, as the settings you would need to use for oval would be VERY different than what works on Road.  I only do road, thus my settings work fairly well for road events (with of course some caveats which are slowly starting to be worked on)

Since you're looking for oval races primarily, here's some settings to try.  It might work a bit better for your situation.

Camera switches (I find this setting only changes when it selects a different camera group from the other configuration, and not when it actually changes the camera in iRacing itself (iRacing will automatically change cameras within the selected group on it's own) thus this theoretically should be renamed to "Time between camera group switches (from config)"  for this to work better, I tend to edit the camera files in iRacing so that I only have 2 or 3 "Groups" that I'll actually use, and then a completely new group, adding in every camera that I'd like to see in the replay at all as it's own group.  Then in iRRD camera config, I set any camera group that is a "Possible" to something <10% and the final group that I made, uses up whatever remaining % is left available.

Lastly, I then keep the time between camera switches at 30 seconds, as that seems to be a decent point where it doesn't look like the camera is randomly flip-flopping all over the place as much.

~ Battle Switches - 30 seconds (any longer and I find if a battle is shorter than what's set here, it won't consider it.  Any shorter, and it jumps around too much.

Time gap - This is where road and oval need a different setting.  Your 0.5 second for oval is good as long as everyone's nice and tight.  However even on oval, I've seen even the leaders gap out even further than .5 seconds often, thus it would no longer select them for a battle.  If you're finding with my other suggestions that it is still jumping around too much, maybe try bumping this up.  Road on the other hand, I found that it works really well by setting it at the same threshold that iRacing throws up the Blue Flag at, which is 1.5 seconds.  Endurance races where people get spread out more, could use a larger margin however.  I generally have it at 1.5 as a minimum, then if the race is longer than 2 hours, I then use the amount of hours as the seconds in this spot.  Seems to work well.

~ Track leader @ start.  I would set this to be the same as however long 2-3 full laps at race pace would be for oval.  On road, about 1/4 lap

~ Track leader @ last lap.  Same as above

~ Battle factor.  Here's where I found actually opening up the battle logic helped get more front-of-pack action, which seems to be contrary to what "Should happen", however some of my other settings may be what cause this to happen.  I would suggest 1.75 at a max, however 1.5 to be preferable if you want to focus on the front packs more.  If you want action from anywhere, but focused mostly on the front, then I'd drop it down to 1, and do what I suggest for the driver stuff below.

~ Duration.  This one was a major irritant for me.  I run a LOT of really long endurance races (24 hour and such) so was hoping to do even a 10% highlight reel of them (2.4 hour highlight for a 24 hour race should be more than good.  However something in the code makes the highlight reels really screw up unless you have this set to as close to 20% of the actual race (green to checker) length.  However long that may be, changes for every race, even if they're theoretically the same length event, but the 20% rule seems to work the best.  This is an issue I brought up with Dean a long time ago, but just work with it until some other more pressing issues get addressed.

~ Incident scan wait ~ This is variable.  Do you want it to focus on off-tracks and little incidents, or only "The big ones".  If you want it to pop out more often, even if it's just a quick glance, to see what happened, then back to the action, I find dropping this to 25 & 1 works really well.  If you want it to focus on only big accidents, then I'd change it to 75 & 5.  It's not really explained well enough for me to understand I think, however I think the scan wait is how long it takes to verify if an incident is actually an incident, and the ignore is if the incident is less than X seconds long.

~ Preferred Drivers.  This is where my settings get VERY different than most, and may be why I have as much luck as I do.  From what I understand, the issue you're having is that replay director doesn't seem to be focusing on the lead pack as much as you would like.  This is what I would suggest.  For each replay that you do, add in the names of the top 5, or 10, or all lead lap finishers, or heck, even the top 25% of the field as preferred drivers, then fill in the checkbox for "Only select battles for my..."  This way, the program will always be looking for those people who are already in the front of the pack at all times for battle selection, and if there is no direct battle (nobody is within the gap # set above) then it will randomly select one of your preferred drivers to focus on, which should be some of the lead pack anyways!

This is something I tend to change for every event, normally keeping only my actual list of preferred drivers (friends, teammates etc) the same all of the time, and adding in everyone that finished on the lead lap.  Yes, this get's time consuming, however if you end up getting a usual group, then there's less editing and such.  If you do replays for multiple series, you can sometimes get away with a text document with the regular leaders for each series, and simply copy/paste into here.

~Show results - I find that it will tend to skip showing people crossing the finish line, (or show final results too quickly) if I don't have more than 10 people, or 50% of the field (whichever is smaller)  However I normally set this to however many people finish on the lead lap and have found great results.

If you wish chris, feel free to pop onto my teamspeak server @ ts.dogsofracing.com and we could chat back and forth a bit easier.

Another option would be if you want to send me a copy of one of your replays that you're working with, and I can see if I can fiddle with some settings on my end to get the type of result you're looking for.

**Comment by LGRDDOG** [comment]
As for downloading the full source file, I believe if you click on the top left where it shows <> code, then make sure that "Master is selected", finally click on "Download as zip" on the right, that should give you a downloadable file that contains everything to do with the program itself, in it's current form.

The other options are other portions of the program that are either still in development, or are simply broken down more, but are compressed and already included in the master.

I could be slightly wrong on this however, but that's my best guess atm ;)

**Comment by LGRDDOG** [comment]
If you wish chris, feel free to pop onto my teamspeak server @ ts.dogsofracing.com and we could chat back and forth a bit easier.

Another option would be if you want to send me a copy of one of your replays that you're working with, and I can see if I can fiddle with some settings on my end to get the type of result you're looking for.

Another alternative is if we feel we're close with something, I could also remote into your PC (or vice-versa) and we could work on it at the same time (I use TeamViewer)

**Comment by ChrisJackson3** [comment]
Source code I'll get with Dean to be certain what I'm getting. Nothing pressing there, just feel it would make things easier if I already have the code. I'm thinking about contacting the computer science dept at the university I went to here and see if I can cobble together a student team for a project or something.

**Comment by ChrisJackson3** [comment]
I can get you the replay to tweak at your leisure, but what method? It's 1.17GB, 113 lap NiS Open Kansas.

**Comment by ChrisJackson3** [comment]
Yes, Oval Class A stock cars. I don't run road at all.

I did a 10 minute highlight with your settings. Not so good. The biggest annoyance is at a start, it switches right after the green to the last car in the lead group, so you see a straggler and not the leaders. Main thing is to focus on leader and preferred cars. I had the thought as you mentioned to add like the top 5-8 cars as preferred (currently only me).

And I want to stop it from going to the last car in line. That makes zero sense.

I'll upload the highlight to YT.

**Comment by LGRDDOG** [comment]
As for getting the replay to me, the size is no issue (especially considering I upload highlight reels almost daily (or at least as often as I can get them with iRacing and DX11 wanting to crash the sim on me lately)

Any method you wish works, I like MEGA, however Dropbox works as well (however you're much more limited for space)  Both work well being free options as well.  Even if you simply sign up for a MEGA account, then I could directly share a folder with you and anytime you put something in there, it automatically syncs between my 2 PC's.

Regardless, any way you wish works for me.  I know email won't work with their paltry 25MB limit, however any of the file hosting websites that will give you a link to share to someone else works well.

Once I get the replay file, I'll see what I can do with the settings to see if I can get it to stop doing what you're describing.  Let me know when the YT video is up as well so I can visually see what you're talking about.

As for TeamSpeak.  I'm normally on and "Available" during the weekdays, when the kids are in school for the most part.  After school, however, it's a touch-and-go thing as I never know when I'll be able to reliably be at the PC with exception of when I'm doing my 3 BES races.

Cheers

**Comment by ChrisJackson3** [comment]
https://www.youtube.com/watch?v=PJJLR28Wpkc

**Comment by vipoo** [comment]
Hi guys,

Sorry I have been offline a little bit.

Please note, I have not any testing with the application with oval races recently - I dont do oval racing.  So it would not surprise me if there are issues that only happen with oval races.

If you are able to share some replay files, and I have the required cars/tracks, I will try and work thru some of the issues mentioned in this topic.  Though I cant give any kind of ETA.

In terms of code, yes you can download the main application by the link mention, but you will also need some of the support projects (eg: iRacingSDK).

The easiest way to get the code, is to use GIT (a source code repository tool that is separate to github - although github have lots of FAQ pages on installing and using).

All the required sub-projects are set up as GIT submodules --- i will not walk through the download process in this topic (it be too long and general).  If you are interested, then i recommend reading thru the help/faq pages on github.  After that, happy to give as much help as I can with download, compiling and executing the code.

Cheers
Dean

**Comment by LGRDDOG** [comment]
Hmm....didn't encounter that one before....I actually use [MEGA.nz](url)

**Comment by ChrisJackson3** [comment]
Okay, that's the MEGA. Got it now. Uploading file.
Account name is Chris Jackson

**Comment by ChrisJackson3** [comment]
MIchel, were you able to get the replay file?

**Comment by LGRDDOG** [comment]
You didn't send me a direct download link, nor do I have your Mega Email address to send you the synced folder authorization.

I can only search for users by their email as well, so your Account Name helps a bit, however doesn't allow me to find you ;)

**Comment by ChrisJackson3** [comment]
onetngator@yahoo.com

Sorry, I have no idea how this MEGA works. Just let me know what you need.

**Comment by LGRDDOG** [comment]
Sorry for the delayed response.  Got a little busy in RL around here!  

If you give me your email that you registered @ MEGA with, then I can send you the shared folder authorization.  Then simply transfer the file from your mega folder, to that one, and I'll automatically get it synced to both of my PC's...

This latest NVidia Update to both Geforce Experience and the Driver itself has pooched my ability to use Shadowplay, which is one of the things I've been battling with over the last week.  Unfortunately it's a known issue by NVIDIA where many games are no longer being recognized as a valid program to capture, so hopefully there's a fix in there soon.  for the meantime, I may have to go back to Bandicam (which hopefully isn't plagued by dreadful FPS which got me to try Shadowplay in the first place) or even (heaven forbid) OBS as a last ditch effort.

I stream all of the time with OBS, so getting that to work is no problem.  Finding a good quality setting with it to be comparable to what I've been doing with Shadowplay is going to be the hard part ;)

**Comment by ChrisJackson3** [comment]
No problem, stuff happens. All this is secondary to RL.

Did you see the email I had posted above? I'll message it to you.

**Comment by ChrisJackson3** [comment]
Tried out ver. 58, seemed to go fine, but had it set to encode a highlight only, and got no highlight reel. It did do the full race, though I didn't encode it, just wanted to see a highlight but got none.

**Comment by MerlinCooper** [comment]
Closed based on the positiv feedback form ChrisJackson3
