### ISSUE TITLE
The byte stream type of the given URL is unsupported.

### ISSUE THREAD

**Issue by ghost** [vipoo/iRacingReplayOverlay.net#90]
Keep getting this error when recording. No matter what program or audio settings I get this error. I used Dxtory and OBS. Please help

**Comment by vipoo** [comment]
Hello,

Sorry to hear you have issues with the app.  

The error message you are getting is due to incompatibility of video and or audio formats.

You need to ensure OBS captures in a format compatible with my app. (MPEG/H.264 video and PCM or uncompressed for the audio).

A fellow iRacing has created a handy PDF file, on setting up the app with OBS - you can find the doc on iRacing's forum:

Its the attachment on the first posting.
http://members.iracing.com/jforum/posts/list/3271807.page

There is a change coming (no ETA), that will support many more video and audio formats, until then you need to select the required format.

Cheers
Dean
