### ISSUE TITLE
nable to determine video file name in 'C:\iRacingVideos' 

### ISSUE THREAD

**Issue by brettswift** [vipoo/iRacingReplayOverlay.net#92]
I created a folder at the root of my C drive to store output files.   I get this error: 

I've changed this to a folder within "my documents"  but not within the iRacing folder itself. 

I will have a separate disk installed this week dedicated to video exports - hoping this will work for me. 

```

Switching to iRacing ....
Begining Test....
Broadcasting keypress ALT+F9 to activate your video capture software
Sending key event ALT+F9
Expecting video file to be written in folder: C:\iRacingVideos
Waiting for 5 seconds
5 Seconds...
4 Seconds...
3 Seconds...
2 Seconds...
1 Seconds...
0 Seconds...
Broadcasting keypress ALT+F9 to deactivate your video capture software
Sending key event ALT+F9
Unable to determine video file name in 'C:\iRacingVideos' - possible wrong working folder
Minimising iRacing

Failure!

```

**Comment by LGRDDOG** [comment]
You also have to make sure that the program you are using to create the videos themselves is outputting to the same folder.  (OBS, FRAPS, NVIDIA Shadowplay etc.)

That error isn't anything wrong with the directory itself, only that it cannot find any video files in that folder when it's testing.

Remember, Replay Director is just that, a DIRECTOR, it only controls iRacing to show what you want.  You still need to use another program to actually capture the video.  BOTH programs have to point to the same directory.

What program (other than iRacing and Replay Director) are you using to record?

**Comment by brettswift** [comment]
I was just about to edit the post as I noticed the print on the right - directions I didn't follow :) 

I'm using ShadowPlay,  and I set the directory to the `C:\users\bswift\videos`  directory that ShadowPlay has in it's config.   Still no dice. 

I tried switching ShadowPlay's working directory to the video folder in case it was putting files there too but didn't work.

**Comment by brettswift** [comment]
Shadow Play is running.   I see the video screen switch to iRacing.   I'm just running the verification now, which I should have run before my first export test..  but it was working and controlling cameras in iRacing etc..   kinda cool.. just the save part isn't configured right.

**Comment by LGRDDOG** [comment]
Alright.  Shadowplay is a bit tricky.

Set shadowplay to the original directory that you wanted, then while iRacing is open, and BEFORE you start Replay Director, hit your ALT+F9.  You should see something pop up saying "Starting Recording" in the top right.  If you don't, then make sure the shadowplay configuration is set to record with ALT+F9.

If you *DO* see that, wait a few seconds, then hit ALT+F9 again, which should stop recording.

Now manually go to the directory you created, and you should see a new folder in there (Which was created by Shadowplay) similar to what mine is (c  program files (x86) iracing iracingsim64dx11.exe)

DO *NOT* Delete that folder.  Instead, in Replay Director, set that new folder as the recording directory, and you should then be able to pass verification.

Silly thing about NVIDIA's Shadowplay, is it creates it's own folder inside the folder you designate for every individual exe for any game it's recording (so yes, iRacing could have any of 4 different directories, due to you being able to use 32 or 64 bit, as well as DX9 or DX11)

I've also found it's much more reliable recording in windowed mode vs full-screen.

One other annoying thing I've noticed with the latest build of NVIDIA's Shadowplay, is you have to actually open GeForce Experience, then disable, and re-enable the "SHARE" option in the top right (beside your login) after any restart of your PC, or else it won't actually work.  Quick test to see if it's even going to be able to detect is to hit ALT+Z, and see if the Share Overlay pops up.  If it doesn't, then you need to do the disable/enable goofiness.  (PS Make sure you are *NOT* in a game when you do that part, or even try opening GeForce Experience, or it will crash your game)

I'm using Shadowplay for all of my highlight reels which you can see @ [KTM Motorsports YouTube](http://youtube.com/user/lgrddog)

**Comment by brettswift** [comment]
Shut it down for the night but I'll give that a go next time. 

It'd be nice to have a walkthrough on different recording devices.  You could detect which one is open even and display a setup / tips button inside the app..  display a markdown file even, that could easily be browsable in the git hub repo,  and slurp in at deploy time into the application.

Just a quick brainstorm. :)

Thanks.. I'll let you know how it goes!

**Comment by brettswift** [comment]
Hmm..  so Shadow Play is weird.   There's a power button in the app but the config settings seem to be back on the main geforce experience page.   confusing. 

alt-f9 doesn't work.. it doesn't start recording and only puts a 'general' file in the folder. 

AlT-F9 is set to "toggle manual recording on/off and save".

**Comment by LGRDDOG** [comment]
When you open the GeForce Experience application, did you click on the down arrow beside "Share" in the top right, then go do "Disable", wait a few seconds, then "Enable" again?

I have to do that EVERY TIME I restart my PC, or else shadowplay will not do anything.  To quickly check if you have to do this, try pressing ALT+Z.  That should bring up the shadowplay menu.  If that does nothing, then you have to do what I said above, and disable, then re-enable.  Doesn't matter if it says that it's already enabled.

After that, then all the config for the recording is in that overlay menu from ALT+Z for shadowplay.  Nothing in the Geforce Experience.  At least that's what I'm experiencing.

The General file would be from Replay Director.  Not Shadowplay.  That means you're testing BOTH at the same time.  Try getting shadowplay working first, without even opening replay director.  That will eliminate any strange findings.

**Comment by brettswift** [comment]
I've been through all the tabs and pages of GeForce Experience and I can't find anything that says Share.   In the top right I see my name on a dropdown button, and to the left of that is a shadowplay button.

**Comment by brettswift** [comment]
GeForce Experience is at version 2.11.4.0

**Comment by brettswift** [comment]
Ok, very strange.  I clicked an option "allow desktop capture.."  and it creates a "Desktop" folder inside the designated shadowplay folder. 

I set the director to that directory (`c:\iRacingVideos\Desktop`) and it the verify video test works......  From your previous note on it creating a directory for 64bit & DX11...   so not sure this will work but I'll try recording a video.

**Comment by brettswift** [comment]
likely not what I want.. the test video recorded the full desktop.  arg.

**Comment by brettswift** [comment]
I was able to get it working.  I had to restart iRacing and get it to stay in full screen mode.   

The app is pretty cool.  It did record a video, but was 5GB on a 4 lap section!   The short highlight one didn't have all the battles, but I kept it to 2 min.. that was about 140 MB - decent.    I'll try another encoded highlight reel that's a little longer and see how it does.   If I get a good one I'll upload it to my youtube channel:  'brettswiftvideos'.   

Thanks for writing this!  (Saw your pit crew app too..  havan't tried it..  seems abandoned.. or was it working 2 years ago and hasn't needed an update!?   Might take a look!)

**Comment by dnetherton** [comment]
Glad to hear you got it working :+1: 

Pit Crew app: yeah i havnt looked at it for a while - and it did have a bug where it crashes, so u end up shouting 'pit crew' - but they left!  Seems appropriate to me - given the way i drive sometimes ;-)
