### ISSUE TITLE
Sound mutes 

### ISSUE THREAD

**Issue by ScottFSR** [vipoo/iRacingReplayOverlay.net#94]
Once Reply dir activates i loose all in sim sounds. I have the correct keys alt/F9 set and if i just record with OBS i have no issues, as soon as i use the replay dir all sounds are muted.

**Comment by MerlinCooper** [comment]
Although your feedback is already a long time ago I was having a look at the issue. Restarted using ReplayDirector 2-3 weeks ago - was not able to reproduce the issue.

The only hypothesis I do have is that in your app.ini file "mute_WhenFocusLost" is set to 1. In that case the iRacing sound would be muted when you click on the ReplayDirector Window because it looses the input focus. 

Make sure that in the followin seeting is in your app.ini file (iRacing Folder) 

`mute_WhenFocusLost=0                    	; set this to 0 to hear sim sounds when another program has the keyboard focus`
