### ISSUE TITLE
SSL/TLS Error

### ISSUE THREAD

**Issue by DrHugoS** [vipoo/iRacingReplayOverlay.net#99]
Got this error

An Error occurred. Details have been Logged
The request was aborted: Could not create SSL/TLS Secure Channel

**Comment by MerlinCooper** [comment]
Not quite sure but could it be that the connection to appveyor.com fails? In any case project has status disabled - not sure how to re-enable it. But very likely only vipoo can do that. 

https://ci.appveyor.com/project/vipoo/iracingreplayoverlay-net/builds/2523024

**Comment by MerlinCooper** [comment]
Due to appveyor configuration / key no longer valid the CI / CD interface is no longer working. 

Starting with #117 the project does compile and start w/o errors although code used for continous integrations / deployment is still included. Supposed to be removed (or reactivated) at a later point of time.
